<?php
print "<html lang=\"php\">";
print "<html lang=\"php\">";
print "<head><title>My Resume</title></head>";
print "<h1>Timothy Dunphy: Senior Systems Engineer</h1>";
print "<p>COGNIZANT TECHNOLOGIES - TEANECK, NJ</p>";
print "<p>SENIOR CLOUD ARCHITECT - FEB 2021 - PRESENT</p>";
print "<p>SYNCHRONOSS TECHNOLOGIES - BRIDGEWATER, NJ</p>";
print "<p>SENIOR DevOps ENGINEER - DEC 2019 – JAN 2021</p>";
print "<p>SYNCHRONOSS TECHNOLOGIES - BRIDGEWATER, NJ</p>";
print "<p>SENIOR DevOps ENGINEER - DEC 2019 – JAN 2021</p>";
print "<p>KPMG LLP - MONTVALE, NJ</p>";
print "<p>SENIOR ASSOCIATE OF SYSTEMS AND INFRASTRUCTURE ENGINEER - AUG 2016 – DEC 2019</p>";
print "<p>NBCUNIVERSAL - ENGLEWOOD CLIFFS, NJ</p>";
print "<p>SENIOR PLATFORM ENGINEER - MAR 2015 - JUL 2016</p>";
print "<p>APTASK - ENGLEWOOD CLIFFS, NJ</p>";
print "<p>SENIOR PLATFORM ENGINEER - MAR 2014 - MAR 2015</p>";
print "<p>TEKMARK GLOBAL SOLUTIONS - RED BANK, NJ</p>";
print "<p>SYSTEMS ADMINISTRATOR - JUL 2013 - MAR 2014</p>";
print "<p>MLB ADVANCED MEDIA - NEW YORK, NY</p>";
print "<p>SYSTEMS ADMINISTRATOR - SEP 2011 - JUN 2013</p>";
